### ISSUE TITLE
Move the OpenEBS OperatorHub listing to upstream

### ISSUE THREAD

**Issue by muratkars** [openebs/helm-operator#6]
Currently OpenEBS is listed as a Community Operator under the OperatorHub https://github.com/operator-framework/community-operators/tree/master/community-operators repository.
When OpenShift is installed, first, it shows the upstream operator on its OperatorHub menu and it takes time for community operators to show up.
OpenEBS is a commercially supported CNCF project and it would be a better fit if it is listed under the https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators repository.

**Comment by muratkars** [comment]
[#2848](https://github.com/openebs/openebs/issues/2848)

**Comment by ksatchit** [comment]
The OpenEBS operator is now available on both community operators and upstream-community-operators till 1.4.0

**Comment by ksatchit** [comment]
The current released version 1.5.0 operator is now available in both community/upstream operators. Closing this issue as we now have parity b/w OpenEBS release & the published operators.
